### ISSUE TITLE
Metric for current queue size?

### ISSUE THREAD

**Issue by jmdacruz** [zerok/celery-prometheus-exporter#17]
I've been using `celery_tasks{state="RECEIVED"}` in an attempt to monitor the current number of queued tasks (basically, what you would see on the "queued tasks" graphic in Flower), but I realize this is not the metric I'm looking for.

Should I be using a different value for `state`? For some reason, I have no data points for `PENDING`. What am I missing?

**Comment by jmdacruz** [comment]
My bad... I guess I need to get the queue size from the backend itself (in my case that would be redis)

**Comment by zerok** [comment]
Hi :) Sorry for the late response. If by "queued task" you mean pretty much everything from received all the way to completed, the easiest way would probably be to look at the backend itself (as you've already mentioned).

As for `PENDING` being empty: Could it be that you have enough workers so that actually nothing is pending long enough for it to show up? Otherwise, could you please describe your setup including what version of celery etc. you're using? Thank you :)

**Comment by jmdacruz** [comment]
You are correct on your assessment for `PENDING`. On "queued tasks" I meant tasks sent by a client but not yet started by any worker. The thing is that `RECEIVED` will only show tasks on the worker's queue (that is, that have been effectively removed from the backend and "sent/received" by a worker), but not the ones that are still waiting on the backend. For these there is no other option than to check the backend itself, but it's actually quite simple: http://docs.celeryproject.org/en/latest/userguide/monitoring.html#monitoring-redis-queues

Thanks!
