### ISSUE TITLE
Request for updated pypi package supporting celery 4.x

### ISSUE THREAD

**Issue by pieterdejaeghere** [zerok/celery-prometheus-exporter#2]
Hi,

Thank you for your work on this module.

I'm hoping you could update the pypi package to include celery 4.x support, that would be a big convenience for me.

Thanks in advance,
Pieter

**Comment by zerok** [comment]
Hi 🙂

Have you already tried https://github.com/zerok/celery-prometheus-exporter/blob/master/Dockerfile-celery4 ? 😊

**Comment by pieterdejaeghere** [comment]
Hi, 
That one is also very specific (==4.0.1), while 4.0.2 was released.

Can you change them to less specific versions like >=3 ?

If you are OK with that, please also update the pypi.python.org package.

Thanks in advance,
Pieter

**Comment by zerok** [comment]
Hi 😃 

Due to some health issues I cannot promise a time-frame but I will try to look into this as soon as possible.

**Comment by zerok** [comment]
Ah, I totally forgot that I had set some rather strict dependency restrictions within the `setup.py`. I will change that to just `>=3` and update the `requirements.txt`-files to use the latest version of the 3.x and 4.x release-branches. I need those in order to create reproducible Docker images. I hope, this is OK for you :-)
