### ISSUE TITLE
Celery 4.x compatibility

### ISSUE THREAD

**Issue by zerok** [zerok/celery-prometheus-exporter#27]
Seems like Celery 4.x requires some slightly different settings to get its data into Prometheus. See #26 for details.

**Comment by javabrett** [comment]
It's not clear to me what (if anything) is outstanding here.  Are there any known issues?

#26 did not help as in that issue it seemed that Celery 4.x was selected and _resolved_ issues rather than created them.

I'm not seeing any Celery 4.x + Prometheus issues currently, but if there are any, let's start listing them out here.

**Comment by zerok** [comment]
Yeah, I also think this is no longer valid. Thanks for testing :)
